---
title: "D19018 manish kumar t-test and ch-square test"
output: html_document
# Name-Manish kumar
# Roll-D19018
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
{
    test = function(data,target)
        {
    #Check whether the passed data is in dataframe format
    if (!is.data.frame(data)) {
        stop("Pass the data as a dataframe")
    }
    #Check whether the passed target is part of the dataframe
    if (!target %in% colnames(data)) {
        stop("The target that you have passed is not part of the dataframe")
    }
    #Check the type of the data frame it should be binary classifier or categorical
    
    #Subset the data without the target
    keep = colnames(data) %in% c(target)
    X <- data[,!keep]
    y <- data[,keep]
    
    #If the data is numeric calculate the t-test p value and store it in a vector
    vect_t=c()
    vect_c=c()
    count_t=1
    count_c=1
    # loop inside the dataset
    for (i in 1:ncol(X)) {
        if (is.numeric(X[,i]))
        # check wether it is numeric 
            {
            #if numeric then performt-test
            t=t.test(X[,i]~y)
            vect_t[count_t]=t$p.value
            # print the t-test with every columns
            print(paste("t" ,colnames(X[i]),vect_t[count_t],sep=" "))
            count_t=count_t+1
            # if it is not numerical then perform chi-square-test 
        }else{
            c=chisq.test(X[,i],y)
            vect_c[count_c]=c$p.value
            # print chi-square test values
            print(paste("c" ,colnames(X[i]),c$p.value,sep =" "))
            count_c=count_c+1
        }
    }
    #If the data is categorical calculate the chi-square test p-value and store it in a vector
    return(vect_t)
}
}   
setwd("C:\\Users\\MANDY\\Desktop")
att=read.csv("attrition.csv")
test(att,"Attrition")

```



